tasnim/urls.py
from re import template
from django.conf.urls import url
from django.contrib import admin
from django.http import request
from django.urls import path
from django.urls.conf import include
from tasnim_main_app.views import *
from django.contrib.auth import login
urlpatterns = [
       path('admin/', admin.site.urls),
       path('home/',home_view,name="home"),
       path('',home_view),
       path('login/',view_login,name="login"),
       path('create_account/',create_account,name="create_account"),
       path('homepage/',home_page,name="home_page"),
       path('homepage/subcat/<slug>',view_subcat,name="subcat_route"),
       path('backhome/',back_home,name="profile_view"),
       path('login/report-home',lambda request: render(request,'fancy_report.html')),
        path('login/fancy_report',json_fancy_report_handler),
       path('login/Outputs/add',OutputCreateView.as_view()),
       path('login/Projects/add',ProjectCreateView.as_view()),
       path('login/Inputs/add',InputCreateView.as_view()),
       path('login/Outputs/delete/<int:id>',OutputDeleteView),
       path('login/Inputs/delete/<int:id>',InputDeleteView,),
       path('login/Projects/delete/<int:id>',ProjectDeleteView,name="delete_projects"),
       path('login/Projects',ProjectListView.as_view()),
       path('login/Inputs',InputListView.as_view()),
       path('login/Outputs',OutputListView.as_view()),
       path('login/Outputs/edit/<int:pk>',OutputUpdateView.as_view(),name='edit_outputs'),
       path('login/Inputs/edit/<int:pk>',InputUpdateView.as_view(),name='edit_inputs'),
       path('login/Projects/edit/<int:pk>',ProjectUpdateView.as_view(),name='edit_projects'),
       path('login/Projects/report',project_report_view),
       path('login/Inputs/detail_report',input_filter_view),
       path('login/Outputs/detail_report',output_filter_view),
       path('login/Inputs/get_report',input_report_view),
       path('login/Outputs/get_report',output_report_view),

]

tasnim_main_app/models.py
from django.db import models
from django.contrib import auth
from django.contrib.auth.models import User
from django.db.models.deletion import DO_NOTHING
from django.db.models.expressions import Subquery
from django.db.models.fields import DateTimeField, IntegerField
from django_jalali.db import models as jmodels
import time
from django.db.models.fields.related import ForeignKey, OneToOneField
class Category(models.Model):
    name=models.TextField(max_length=200)
    url=models.TextField(max_length=200)
    def __str__(self) -> str:   
        return self.name

class Person(models.Model):
    full_name=models.TextField(max_length=200,verbose_name='نام شخص')
    card_numbers=models.TextField()
    total_donations=models.IntegerField(default=0)
    
    
class MyUser(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    dated_joined=DateTimeField(auto_created=True)
    address=models.TextField(max_length=200)
    zip_code=models.TextField(max_length=200)
    def __str__(self) -> str:
        return self.username
class Donor(models.Model):
    name=models.CharField(max_length=200)
    card_number=models.CharField(max_length=200)
class Project(models.Model):
    نام_پروژه=models.CharField(max_length=30)    
    تاریخ=jmodels.jDateField(auto_created=True)
    توضیحات=models.TextField(max_length=300)

    def __render__(self)->str:
        return "نام_پروژه %s تاریخ اضافه شدن %s تاریخ اضافه شدن %s ".format(self.نام_پروژه,self.تاریخ,self.توضیحات)
    def __str__(self) -> str:
        return self.نام_پروژه
class Input(models.Model):
    حساب_خیر=models.TextField(max_length=16)
    نام_خیر=models.TextField(max_length=100)
    مبلغ=models.DecimalField(max_digits=30,decimal_places=0)
    نام_ورودی=models.TextField(max_length=300,null=True,verbose_name="یاد نشان")
    تاریخ=jmodels.jDateField(auto_created=True)
    input_project=models.ForeignKey(Project,on_delete=models.CASCADE,null=True,verbose_name="پروژه",related_name="related_proj")
    def __name__(self)->str:
        return "Input"
    def __str__(self) -> str:
        return  self.نام_ورودی+" "+self.نام_خیر
class Output(models.Model):
    related_project=models.ForeignKey(Project,on_delete=models.CASCADE,null=True,verbose_name='پروژه مربوطه',related_name="پروژه_مربوطه")
    حساب_مقصد=models.TextField(max_length=16)
    نام_ورودی=models.TextField(max_length=300)
    مبلغ=models.DecimalField(max_digits=30,decimal_places=2)
    تاریخ=jmodels.jDateField(auto_created=True,default="0")
    def __name__(self)->str:
        return "Output"
    def __str__(self) -> str:
        return self.حساب_مقصد+" "+self.نام_ورودی

templates/create.html
{%extends 'logged_in.html'%}
{%load static%}

<body>
    

{%block shit%}

<div class="container" style="position: absolute;left:75%;top:100%;background-color: rgba(199, 199, 199, 0.685);padding: 50px;">
<div class="address-container" style="position:relative;top:50%;left:0%;width:100%">

</div>
    <form method="POST" enctype="multipart/form-data">
    
        {% csrf_token %}
    
        {{ form.as_p }}
        
        <input type="submit" value="ثبت">
    </form>
    <script>
        $(document).ready(function (){
            for (let element of document.body.getElementsByTagName("*")){
                if (element.tagName=="TEXTAREA" || element.tagName=="INPUT" && element.id!="search-text"){
                    element.classList.add("input-text")
                    element.classList.add("main_style")
                }
                console.log(element.tagName)
            }
        })
    </script>
</div>
<script>
    document.getElementById("background-image-2").style.opacity="100%"
</script>
{%endblock shit%}

</body>

templates/fancy_report.html
{%extends 'logged_in.html'%}
{%load static%}

<body>
    

{%block shit%}

<div class="container" >

<div class="sub-container" style="position:absolute;left:0%;background-color:rgb(245, 245, 245);opacity:80%;border-radius:25px;padding:50px;height: 100x;width:34vh;border-width: 4px;border-bottom-width:5px;border-bottom-color:rgb(138, 138, 138)">



    <button ></button>
    <form  id="filter-form" onload="document.filter-form.submit()" method="POST" >    {%csrf_token%}
    
    
        <p><label >از تاریخ</label> <input type="text" name="start_date"  id="id_تاریخ" class="input-text main_style">
        <p><label> تا تاریخ</label> <input type="text" name="end_date"  id="id_نام_پروژه" class="input-text main_style"></p>
      
        <p><label >نام پروژه</label> <input type="text" name="project_name"  id="id_تاریخ" class="input-text main_style">
     

          </span>
        </p>
        
      <input type="submit" value="اعمال کن" class="input-text main_style">

    </form>
    <script src="{%static 'tasnim_main_app/send_fancy_response.js'%}">

    </script>
 


</div>

<div id = "results_chart_container" style="position: absolute;top:50%;left:30%;width:1000px;height:500px">
  <div style="position: absolute; left:40vhx ">
<label > دخل<span id="inputs_sum">  </span></label>
<label > خرج <span id="outputs_sum">  </span></label>
</div>
  <canvas id="results_chart" ></canvas>

</div>
{%endblock shit%}

</body>

templates/list_all.html
{%extends 'logged_in.html'%}
{%load static%}

<body>
    

{%block shit%}
    
<style>
    table, th, td {
      border: 1px solid black;
      border-collapse: collapse;
    }
</style>


<table style="float: inline-end;border-width: 1px;border-style: solid;position: absolute;left:60vh" >

        <tr>
            {%if page_obj.0.نام_پروژه%}   
            <th>
            <span style="position:relative;top:15%;display:block;text-align:center;">نام پروژه</span>      
            </th>
            {%endif%}
            {%if page_obj.0.نام_خیر%}   
            <th>
            <span style="position:relative;top:15%;display:block;text-align:center;">نام خیر</span>      
            </th>
            {%endif%}
            <th>
                <span style="position:relative;top:15%;display:block;text-align:center;"> تاریخ  </span>      
            </th>
            {% if page_obj.0.توضیحات%}
            <th>
                 <span style="position:relative;top:15%;display:block;text-align:center;">توضیحات </span>   
 
             </th>
             {%endif%}
            {%if page_obj.0.مبلغ%}
            <th>
            <span style="position:relative;top:15%;display:block;text-align:center;"> مبلغ  </span>      
            </th>
            {%endif%}
      
            {%if page_obj.0.حساب_مقصد%}   
                <th>
                <span style="position:relative;top:15%;display:block;text-align:center;"> حساب مقصد  </span>      
                </th>
            {%endif%}
            {%if page_obj.0.حساب_خیر%}   
            <th>
            <span style="position:relative;top:15%;display:block;text-align:center;"> حساب خیر </span>      
                </th>
            {%endif%}
           
            <th>
                عملیات
            </th>
            
        </tr>
    
    {%for object in page_obj%}
    <tr>
    {%if page_obj.0.نام_خیر%}   
    <td>   
    <span>{{object.نام_خیر}}</span>      
    {%endif%}

    </td>
        {%if page_obj.0.نام_پروژه%}   
        <td>   
        <span>{{object.نام_پروژه}}</span>      
        </td>
        {%endif%}
        <td>
        <span>{{object.تاریخ}} </span>      
        </td>
       
  
    {%if page_obj.0.توضیحات%}   
    <td>   
    <span>{{object.توضیحات}}</span>      
    </td>
    {%endif%}

    {%if object.مبلغ%}
    <td title="quantity">
    <span>{{object.مبلغ}}   </span>      
    </td>
    {%endif%}

    {%if object.حساب_مقصد%}   
        <td>
        <span>  {{object.حساب_مقصد}} </span>      
    </td>
    {%endif%}

    {%if object.حساب_خیر%}   
        <td>
        <span>  {{object.حساب_خیر}}</span>      
    </td>
    {%endif%}

<td>
    {%if object.حساب_خیر%}   
    
    <div name id="control" style="position:relative;left:10%">
        <a id="remove-link" href="/login/Inputs/delete/{{object.pk}}">
            <i class="fa fa-trash" style="color: red;" ></i>
        </a>
        <a id="update-link" href="/login/Inputs/edit/{{object.pk}}">
            <i class="fa fa-edit" style="color: blue;"></i>
        </a>    
    </div>
    {%endif%}
    
    {%if object.نام_پروژه%}   
        <div name id="control" style="position:relative;left:10%">
        <a id="remove-link" href="/login/Projects/delete/{{object.pk}}">
        <i class="fa fa-trash" style="color: red;" ></i>
        </a>

        
        <a id="update-link" href="/login/Projects/edit/{{object.pk}}">
            <i class="fa fa-edit" style="color: blue;"></i>
        </a>    
        </div>
    {%endif%}
    {%if object.حساب_مقصد%}   

        <div name id="control" style="position:relative;left:10%">
        <a id="remove-link" href="/login/Outputs/delete/{{object.pk}}">
        <i class="fa fa-trash" style="color: red;" ></i>
        </a>
        <a id="update-link" href="/login/Outputs/edit/{{object.pk}}">
            <i class="fa fa-edit" style="color: blue;"></i>
        </a>    
        </div>
    {%endif%}

    </td>
</tr>

{%endfor%}
<div class="pagination main_style"  style="position:absolute;left:15%;width:25vh;background-color: rgb(255, 255, 255);z-index: 5;">

    <span class="current "  style="width: 150px; " >
        صفحه {{ page_obj.number }}  از {{ page_obj.paginator.num_pages }}
    </span>
    <span class="step-links">
        {% if page_obj.has_previous %}
        
            <a href="?page={{ page_obj.previous_page_number }}"> قبلی </a>
        {% endif %}
            

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">بعدی </a>
   
        {% endif %}
    </span>
</div>

</table> 
{%endblock shit%}

</body>

templates/logged_in.html
{% load static %}

<html>

<head>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{%static 'tasnim_main_app/styles.css'%}">
    <link rel="stylesheet" href="{%static 'tasnim_main_app/fontawesome/css/all.css'%}">
    <script src="{%static 'tasnim_main_app/jquery-3.6.0.min.js' %}"></script>
    <link href="https://cdn.jsdelivr.net/gh/rastikerdar/vazir-font@v30.1.0/dist/font-face.css" rel="stylesheet" type="text/css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>


    
    
</head>

<body>
        
    <img id="background-image-2" src="{%static 'tasnim_main_app/images/back2.jpeg'%}"  style="z-index: -4;;opacity: 80%;;width: 100%;height: 100%;position:absolute;" >
        
        <div class="header-first" style="position:absolute;top:0;z-index: 0;left:0%; border-radius:0px;height:18%;background-color:#f7f7f7">
         
            <img style="height:100%;position:absolute;top:0%;left:0%;z-index: 0;opacity: 100%;" src="{%static 'tasnim_main_app/images/logo.png'%}">
            {%for tab in tab_data%}
            <a href="/login/{{tab.cat.url}}" style="text-decoration: none">
            <div  class="category-nav-bar" style="font-size:large;">
                {{tab.cat.name}} 
            <div class="dropdown"  style="margin-top:40px">
            </a>
            <a href="/login/{{tab.cat.url}}/add">
                    اضافه<i class="fa fa-plus" style="color:#3a7fe665;position:relative;top:5px;left:10px;font-size:24px"></i>
            </a>
            <br>
            
                </div>
            </div>
   
            {%endfor%}
                <div  class="category-nav-bar">
                    فیلتر 
                    <div class="dropdown"  style="margin-top:40px;height:100px">
                    </a>
                    
                    <br>
                    <a href="/login/Inputs/detail_report">
                         ورودی ها  <i class="fa fa-arrow-left" style="color:#3a7fe665;position:relative;top:5px;left:10px;font-size:24px"></i>
                    </a>
                    <br>
                    <a href="/login/Outputs/detail_report">
                            خروجی ها <i class="fa fa-arrow-right" style="color:#3a7fe665;position:relative;top:5px;left:10px;font-size:24px"></i>
                    </a>
                    <a href="/login/report-home" style="text-decoration: none;color:black ">

                      
                            
                    </a>
                   
                    </div>
                    
                    </div>
                    <div class="category-nav-bar" style="font-size: large;position:relative;z-index:0;left:0vh;top:15 vh" aria-placeholder="">
                        <a href="/login/report-home"> گزارشات</a>

                        <div class="dropdown"  style="margin-top:40px;height:180px">
                        </a>
                        <a href="/login/report-home">
                               نمای کلی<i class="fa fa-tasks" aria-hidden="true" style="color:#002b6b;position:relative;top:5px;left:10px;font-size:24px"></i>
                        </a>
                  
                        <br>
                        <br>
                    
                        <a href="/login/Projects/report">
                          گزارش دلخواه      <i class="fa fa-clock" style="color:#3a7fe665"></i>
                            </a>
                                 
                        <br>
                        <br>
                
                       
                        </div>
                        
                 </div>
                 <a href="/backhome" style="text-decoration: none;color:black ">

                    <div class="category-nav-bar" style="position:absolute;left:92%;top:15%;z-index:0" aria-placeholder="">
                        <i class="fas fa-home" style="color: blue;">    
                        </i>
                        <br>خانه
                        <div style="position:relative;font-size: small;left:110%">
                       </div>
                </a>
                    </div>
                
                </div>
     
              
      </div>

         
   
            </div>
            
            </div>
         </a>
  


                 

     
    </div>
    <div id="layer " class="background-layer " style="background-color:white; ">

        {%block shit%} 
        
        {%endblock shit%}

        <div>

</body>
{%block sidebar%}



{%endblock sidebar%}
</html>

templates/login.html
{% load static %}
<link rel="stylesheet" href="{%static 'tasnim_main_app/styles.css'%}">

<!DOCTYPE html>
<html>
<head> 
       <meta name="viewport" content="width=1920px, initial-scale=1.0">
</head>

<body>
    <img src="{%static 'tasnim_main_app/images/background-image.png'%}" style="opacity: 50%;;width: 100%;height: 100%;top:0%;position:absolute;left:0%" >

    <div class="square">
        <div id="start" class="login main_style " style="background-color:#f7f7f7;top:20%;position:absolute;height:55vh;width:36vh; border-width:8px ">
            <img style="height:180px;position:absolute;top:2%;z-index:3" src="{%static 'tasnim_main_app/images/logo.png'%}">
            

            <form action="/login/" method="post">{%csrf_token%}
                <br>
                <br>
                <br>
                <em>
                <input id="username-field" type="text" name="username" placeholder="Username" style="top:120% ; position:relative " class="main_style input-text ">
                <br>


                <input id="password-field1" name="password" type="password" placeholder="Password " style="top:120% ; position:relative " class="main_style input-text ">
                <br>
                </em>

                <em style="left: 13vh;position:absolute ">

                <button style="border-width: 2px;" type="submit" class="main_style button"><p>Login</p> </button>
                <span  style="color:red;font-size:medium;font-family:Georgia, 'Times New Roman', Times, serif">{{error}}</span>
                </em>
            </form>
     


            </p>
        </div>
    </div>
</body>

</html>

<style>

</style>
<script type="text/javascript " src="{%static 'tasnim_main_app/jsscript.js'%} ">
</script>

templates/profile.html
{%extends 'logged_in.html'%}
{%load static%}
<head >
    <link rel="stylesheet" href="{%static 'tasnim_main_app/styles.css'%}">
</head>

{%block sidebar%}

</div>
    <div >

 
</div>
{%endblock sidebar%}

</div>

templates/report.html
{%extends 'logged_in.html'%}
{%load static%}

<body>
    


{%block shit%}
<div style="position: absolute;left:50px" >
<form  id="filter-form"  action="/login/Projects/report" method="POST" >    {%csrf_token%}
    
    
       <p><label >از تاریخ</label> <input type="text" name="start_date"  id="id_تاریخ" class="input-text main_style">
       <p><label> تا تاریخ</label> <input type="text" name="end_date"  id="id_نام_پروژه" class="input-text main_style"></p>
     
    

    
       </p>
       
     <input type="submit"  value="اعمال کن" class="input-text main_style">
        
   </form>
</div>
<table style="top:-20vh;position:relative;left:75vh ; font-size: 18px;">
<thead>
      
       <tr>   <td>نام  </td>  <td> ورودی</td> <td> خروجی</td> </tr>
</thead>
       <tbody></tbody>
{%for object in proj_total_finance%}

           <tr>
<td>
              {{object.0.نام_پروژه}}
       </td>       
           <td>{{object.1}}            </td>
           <br>
           <td>{{object.2}}            </td>
       </tr>
   
           {%endfor%}
</div>
<script>
       function beautify_number(x){
              return x.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",")
       }
       for (data of document.getElementsByTagName("TD")){
              data.innerHTML=beautify_number(data.innerHTML)
       }
</script>     
{%endblock shit%}
</table>
</body> 

templates/report_filter_inputs.html
{%extends 'logged_in.html'%}
{%load static%}

<body>
    

{%block shit%}

<div class="container" >
  <table style="position: absolute; left:30%" id="results-table">
    <tr>
      <th>
        نام خیر
      </th>
      <th>
        مبلغ
      </th>
      <th>
        شماره کارت
      </th>
      <th>
        تاریخ
      </th>
      <th>
        عملیات
      </th>
      <th style="position: relative; left:5vh"> 
        <label for="جمع"></label>
        <em id='sum'>0</em>
        جمع
      </th>
    </tr>
    <tbody id="tbody">


        
    </tbody>
   
   </table>

<div class="sub-container" style="position:absolute;left:0%;background-color:rgb(245, 245, 245);opacity:80%;border-radius:25px;padding:50px;height: 100x;width:30vh;border-width: 4px;border-bottom-width:5px;border-bottom-color:rgb(138, 138, 138)">

    


    <form  id="filter-form" method="POST">    {%csrf_token%}
    
    
        <p><label >از تاریخ</label> <input type="text" name="start_date"  id="id_تاریخ" class="input-text main_style">
        <p><label> تا تاریخ</label> <input type="text" name="end_date"  id="id_نام_پروژه" class="input-text main_style"></p>
      
        <p><label >نام خیر</label> <input type="text" name="donor_name"  id="id_تاریخ" class="input-text main_style">
          <p><label> نام پروژه </label> <input type="text" name="project_name"  id="id_نام_پروژه" class="input-text main_style"></p>

        <p><label> شماره کارت</label> <input type="text" name="card_number"  id="id_نام_پروژه" class="input-text main_style"></p>
          <span>
            <label >   مبلغ کران پایین</label>
          <input class="input-text main_style"  type="number" name="min" value="0" id="start">
          <label > مبلغ کران بالا</label>

          <input class="input-text main_style" type="number" name="max"  value="0" id="end">
          </span>
        </p>
     
      <input type="submit" value="اعمال کن" class="input-text main_style">

    </form>
    <script src="{%static 'tasnim_main_app/filter_inputs.js'%}">

    </script>
               <script>
                function beautify_number(x){
                       return x.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",")
                }
                for (data of document.getElementsByTagName("TD")){
                       data.innerHTML=beautify_number(data.innerHTML)
                }
         </script>     
 

        
</div>


{%endblock shit%}

</body>

templates/report_filter_outputs.html
{%extends 'logged_in.html'%}
{%load static%}

<body>
    

{%block shit%}

<div class="container" >
  <table style="position: absolute; left:30%" id="results-table">
    <tr>
      <th>
        نام  پروژه
      </th>
      <th>
        مبلغ
      </th>
      <th>
        شماره کارت
      </th>
      <th>
        تاریخ
      </th>
      <th>
        عملیات
      </th>
      <th style="position: relative; left:5vh"> 
        <label for="جمع"></label>
        <em id='sum'>0</em>
        جمع
      </th>
    </tr>
    <tbody id="tbody">


        
    </tbody>
   
   </table>

<div class="sub-container" style="position:absolute;left:0%;background-color:rgb(245, 245, 245);opacity:80%;border-radius:25px;padding:50px;height: 100x;width:34vh;border-width: 4px;border-bottom-width:5px;border-bottom-color:rgb(138, 138, 138)">

    


    <form  id="filter-form" method="POST" >    {%csrf_token%}
    
    
        <p><label >از تاریخ</label> <input type="text" name="start_date"  id="id_تاریخ" class="input-text main_style">
        <p><label> تا تاریخ</label> <input type="text" name="end_date"  id="id_نام_پروژه" class="input-text main_style"></p>
      
        <p><label >نام پروژه</label> <input type="text" name="project_name"  id="id_تاریخ" class="input-text main_style">
        <p><label> شماره کارت</label> <input type="text" name="card_number"  id="id_نام_پروژه" class="input-text main_style"></p>
          <span>
            <label >   مبلغ کران پایین</label>
          <input class="input-text main_style"  type="number" name="min" value="0" id="start">
          <label > مبلغ کران بالا</label>

          <input class="input-text main_style" type="number" name="max"  value="0" id="end">
          </span>
        </p>
        
      <input type="submit" value="اعمال کن" class="input-text main_style">

    </form>
    <script>
      function beautify_number(x){
             return x.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",")
      }
      for (data of document.getElementsByTagName("TD")){
             data.innerHTML=beautify_number(data.innerHTML)
      }
</script>     
    <script src="{%static 'tasnim_main_app/filter_outputs.js'%}">

    </script>
 

        
</div>


{%endblock shit%}

</body>

templates/signup.html
{% load static %}
<link rel="stylesheet" href="{%static 'tasnim_main_app/styles.css'%}">

<!DOCTYPE html>
<html>


<body>

    <div class="square">
        <img style="height:90px;position:absolute;top:30%" src="{%static 'tasnim_main_app/images/logo.png'%}">

        <div id="start" class="login main_style " style="top:20%;position:absolute;height:550px;width:400px; border-width:8px ">


            <form action="/create_account/" method="post">{%csrf_token%}
                <br>
                <br>
                <br>
                <input id="username-field" type="text" name="username" placeholder="Username" style="top:120% ; ; position:relative " class="main_style input-text ">
                <br>


                <input id="password-field1" name="password" type="password" placeholder="Password " style="margin-left:0px" class="main_style input-text ">

                <br>
                <input id="password-field2" name="confirm_password" type="password" placeholder="Confirm Password " style="margin-left:0px" class="main_style input-text ">


                <em style="top: 100px ; left: 100px; ; position:relative ">
               
                    <button type="submit" class="main_style button"><p>Signup</p> </button>
                    <span style="color:red;font-size:medium;position:relative;left:0%">{{error}}</span>
                </em>



            </form>
            </p>
        </div>
    </div>

</body>

</html>

<style>

</style>
<script type="text/javascript " src="{%static 'tasnim_main_app/jsscript.js'%} ">
</script>